-- AlterTable
ALTER TABLE "Farmer" ADD COLUMN     "recent_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP;

-- AlterTable
ALTER TABLE "Manager" ADD COLUMN     "recent_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP;

-- AlterTable
ALTER TABLE "Product" ADD COLUMN     "wholeImages" TEXT[];

-- AlterTable
ALTER TABLE "SuperManager" ADD COLUMN     "recent_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP;

-- AlterTable
ALTER TABLE "User" ADD COLUMN     "recent_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP;

-- AlterTable
ALTER TABLE "Writer" ADD COLUMN     "recent_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP;
